<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved. 
 * @author Magerubik Team <info@magerubik.com> 
 * @package Magerubik_Productslider
 */
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$sliderlist = $block->getList();
$idBlock = uniqid();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<?php if(count($sliderlist)>0){ ?>
<div id="tab-container-<?=$idBlock?>" class="productslider tabslide">
    <ul class='list-tab'>
        <?php
        $prefixStr = '#productslider';
        foreach ($sliderlist as $item)
        {
            $hrefurl = $prefixStr . $item->getId();
            $title = $item->getTitle();
            ?>
            <li class='tab' data-cat='<?php echo $item->getCategoryId(); ?>' data-type='<?php echo $item->getTypeId(); ?>' data-active="<?=$item->getId()?>"><span><?=$title?></span></li>
        <?php } ?>

    </ul>
	<div class="tabslide-content">
		<div class="double-bounce-spinner ajax_loading_<?php echo $idBlock?>" style="display:none" data-url="<?php echo $this->getUrl('productslider/index/ajax')?>">
			<div class="double-bounce1"></div>
			<div class="double-bounce2"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
    require(["jquery"], function($){
		function firstTabAjax() {
			var el = $('#tab-container-<?php echo $idBlock?> .list-tab .tab').first();
			var type =el.attr('data-type');
			var catId =el.attr('data-cat');
			var tabId =el.attr('data-active');
			el.addClass('active');
			sendAjax(type, catId, tabId);
			el.addClass('loaded');
			var contentActive = '#productslider' + el.attr('data-active');
			$('#tab-container-<?php echo $idBlock?> .mst-content-tab').removeClass('active');
			$('#tab-container-<?php echo $idBlock?> .tabslide-content').find(contentActive).addClass('active');
		}
		firstTabAjax();
		$('#tab-container-<?php echo $idBlock?> .list-tab .tab').click(function() {			
			if($(this).hasClass('active')) return;
			$('#tab-container-<?php echo $idBlock?> .list-tab .tab').removeClass('active');
			$(this).addClass('active');
			if(!$(this).hasClass('loaded')){
				var type =$(this).attr('data-type');
				var catId =$(this).attr('data-cat');
				var tabId =$(this).attr('data-active');
				sendAjax(type, catId, tabId);
				$(this).addClass('loaded');
			}
			var contentActive = '#productslider' + $(this).attr('data-active');
			$('#tab-container-<?php echo $idBlock?> .mst-content-tab').removeClass('active');
			$('#tab-container-<?php echo $idBlock?> .tabslide-content').find(contentActive).addClass('active');
		});
		function sendAjax(type, catId, tabId) {
			$('.ajax_loading_<?php echo $idBlock?>').show();
			$.ajax({
				url : $('.ajax_loading_<?php echo $idBlock?>').attr('data-url'),
				dataType : 'json',
				type : 'POST',
				data: { type: type, catId: catId, tabId: tabId }			
			}).done(function (data) {					
				$('.ajax_loading_<?php echo $idBlock?>').hide();
				$('#tab-container-<?php echo $idBlock?> .tabslide-content').append(data.html_result);
				$('#tab-container-<?php echo $idBlock?> .tabslide-content').find('#productslider'+tabId).addClass('active');
				$('#tab-container-<?php echo $idBlock?> .tabslide-content').find("[data-role=tocart-form], .form.map.checkout").catalogAddToCart();
			});
	    }
    });
</script>
<form data-role="tocart-form" method="post" style="display:none;"></form>
<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				}
			}
	}
</script>
<?php } ?>