<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved. 
 * @author Magerubik Team <info@magerubik.com> 
 * @package Magerubik_Productslider
 */
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$sliderlist = $block->getList();
$prefixStr = '#productslider';
if($sliderlist) {
  foreach ($sliderlist as $item) {
    $processed = [];
    $hrefurl = $prefixStr . $item->getId();
    $tabdivid = str_replace('#','',$hrefurl);
    ?>
    <div id="<?=$tabdivid?>" class="mr-list-slider" data-cat='<?php echo $item->getCategoryId(); ?>' data-type='<?php echo $item->getTypeId(); ?>' data-active="<?=$item->getId()?>">
        <h2><span><?=$item->getTitle()?></span></h2>
		<div class="double-bounce-spinner ajax_loading_<?=$tabdivid?>" data-url="<?php echo $this->getUrl('productslider/index/ajax')?>">
			<div class="double-bounce1"></div>
			<div class="double-bounce2"></div>
		</div>
	</div>
<script type="text/javascript">
require(["jquery"], function($){
	function firstAjax() {
			var el = $('#<?= $tabdivid; ?>');
			var type =el.attr('data-type');
			var catId =el.attr('data-cat');
			var tabId =el.attr('data-active');
			sendAjax(type, catId, tabId);
	}
	firstAjax();
	function sendAjax(type, catId, tabId) {
			$.ajax({
				url : $('.ajax_loading_<?=$tabdivid?>').attr('data-url'),
				dataType : 'json',
				type : 'POST',
				data: { type: type, catId: catId, tabId: tabId,list:1 }			
			}).done(function (data) {					
				$('.ajax_loading_<?=$tabdivid?>').hide();
				$('#<?=$tabdivid?>').append(data.html_result);
				$('#<?=$tabdivid?>').find("[data-role=tocart-form], .form.map.checkout").catalogAddToCart();
			});
	    }
    });
</script>
<?php } ?>
<form data-role="tocart-form" method="post" style="display:none;"></form>
<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				}
			}
	}
</script>
<?php } ?>