<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved. 
 * @author Magerubik Team <info@magerubik.com> 
 * @package Magerubik_Productslider
 */
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_themeHelper = $this->helper('Magerubik\All\Helper\Data');
$sliderlist = $block->getList();
$idBlock = uniqid();
?>
<?php if(count($sliderlist)>0){ ?>
<div id="tab-container-<?=$idBlock?>" class="productslider tab-vertcal">		
	<h3 class="subtitle"><span class="a-mobile tab-trigger tab-trigger-<?php echo $idBlock?>"><i class="fa fa-bars"></i></span><?php echo $block->getTitle(); ?></h3>
	<ul class='list-tab-vertcal'>	
		<?php
		$prefixStr = '#productslider';
		foreach ($sliderlist as $item)
		{
			$hrefurl = $prefixStr . $item->getId();
			$title = $item->getTitle();
			?>
			<li class='tab'  data-cat='<?php echo $item->getCategoryId(); ?>' data-type='<?php echo $item->getTypeId(); ?>' data-active="<?=$item->getId()?>"><span><?=$title?></span></li>
		<?php } ?>
	</ul>
	<div class="tab-vertcal-content">
		<div class="double-bounce-spinner ajax_loading_<?php echo $idBlock?>" style="display:none" data-url="<?php echo $this->getUrl('productslider/index/ajax')?>">
			<div class="double-bounce1"></div>
			<div class="double-bounce2"></div>
		</div>
	</div>
</div>
<form data-role="tocart-form" method="post" style="display:none;"></form>
<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				}
			}
	}
</script>
<script type="text/javascript">
    require(["jquery"], function($){
		function firstVertcalTabAjax() {
			var el = $('#tab-container-<?php echo $idBlock?> .list-tab-vertcal .tab').first();
			var type =el.attr('data-type');
			var catId =el.attr('data-cat');
			var tabId =el.attr('data-active');
			el.addClass('active');
			sendAjax(type, catId, tabId);
			el.addClass('loaded');
			var contentActive = '#productslider' + el.attr('data-active');
			$('#tab-container-<?php echo $idBlock?> .mst-content-tab').removeClass('active');
			$('#tab-container-<?php echo $idBlock?> .tab-vertcal-content').find(contentActive).addClass('active');
		}
		firstVertcalTabAjax();
		$('#tab-container-<?php echo $idBlock?> .list-tab-vertcal .tab').click(function() {			
			if($(this).hasClass('active')) return;
			$('#tab-container-<?php echo $idBlock?> .list-tab-vertcal .tab').removeClass('active');
			$(this).addClass('active');
			if(!$(this).hasClass('loaded')){
				var type =$(this).attr('data-type');
				var catId =$(this).attr('data-cat');
				var tabId =$(this).attr('data-active');
				sendAjax(type, catId, tabId);
				$(this).addClass('loaded');
			}
			var contentActive = '#productslider' + $(this).attr('data-active');
			$('#tab-container-<?php echo $idBlock?> .mst-content-tab').removeClass('active');
			$('#tab-container-<?php echo $idBlock?> .tab-vertcal-content').find(contentActive).addClass('active');
		});
		function sendAjax(type, catId, tabId) {
			$('.ajax_loading_<?php echo $idBlock?>').show();
			$.ajax({
				url : $('.ajax_loading_<?php echo $idBlock?>').attr('data-url'),
				dataType : 'json',
				type : 'POST',
				data: { type: type, catId: catId, tabId: tabId,vertcal:1 }			
			}).done(function (data) {					
				$('.ajax_loading_<?php echo $idBlock?>').hide();
				$('#tab-container-<?php echo $idBlock?> .tab-vertcal-content').append(data.html_result);
				$('#tab-container-<?php echo $idBlock?> .tab-vertcal-content').find('#productslider'+tabId).addClass('active');
				$('#tab-container-<?php echo $idBlock?> .tab-vertcal-content').find("[data-role=tocart-form], .form.map.checkout").catalogAddToCart();
			});
	    }
		$('.tab-trigger-<?php echo $idBlock?>').click(function() {
			$('#tab-container-<?php echo $idBlock?> .list-tab-vertcal').slideToggle(200);
		});	
		$('.tab-trigger-link').click(function() {
			$('.list-tab-vertcal').slideUp(200);
		});	
    });
</script>
<?php } ?>