<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved. 
 * @author Magerubik Team <info@magerubik.com> 
 * @package Magerubik_Productslider
 */

namespace Magerubik\Productslider\Model\ResourceModel;


use Magento\Framework\Stdlib\DateTime\DateTime;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\Model\ResourceModel\Db\Context;
use Magerubik\Productslider\Model\SliderFactory as Model;

class Slider extends AbstractDb{
    /**
     * @var \Magento\Framework\Stdlib\DateTime\DateTime
     */
    protected $_date;
    protected $_model;
    public function __construct (Context $context,DateTime $dateTime,Model $model,$rescourcePrefix = null)
    {
        parent::__construct ($context,$rescourcePrefix);
        $this->_date = $dateTime;
        $this->_model = $model;
    }

    protected function _construct()
    {
        $this->_init('magerubik_productslider_slider','productslider_id');
    }

    /**
     * Validate Data
     */
    protected function _beforeSave (\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::_beforeSave ($object); // TODO: Change the autogenerated stub
    }

    /**
     * Load data using productslider_id by default
     *
     * @param \Magento\Framework\Model\AbstractModel $object
     * @param mixed $value
     * @param string $field
     * @return $this
     */
    public function load (\Magento\Framework\Model\AbstractModel $object, $value, $field = null)
    {
        if (!is_numeric($value) && is_null($field)) {
            $field = 'productslider_id';
        }

        return parent::load($object, $value, $field);
    }
}